### ISSUE TITLE
Error: Failed to start platform.

### ISSUE THREAD

**Issue by diegodrf** [linkdotnet/LINQMarbles#11]
The application is not working well locally.

After the new architecture organization uses multiple projects, the application is not able to access some files.

At the browser console log the message is:

> Uncaught (in promise) Error: Failed to start platform. Reason: TypeError: Failed to fetch dynamically imported module: http://localhost:5000/_framework/dotnet.js
    at blazor.web.js:1:174308
    at async Es.startWebAssemblyIfNotStarted (blazor.web.js:1:171701)

Some files are not loading properly.
![image](https://github.com/linkdotnet/LINQMarbles/assets/21007712/530cb044-a880-4b5d-8add-7b7d4d3e3c97)

**Comment by linkdotnet** [comment]
Can you make a hard reload or try to run it in incognito tab?

**Comment by diegodrf** [comment]
I tried both before opening the issue.
The print screen attached was shot from the incognito tab.

**Comment by linkdotnet** [comment]
Interesting. It works for me locally via `dotnet watch` as well as `dotnet run` and just using the UI.

<img width="1512" alt="image" src="https://github.com/linkdotnet/LINQMarbles/assets/26365461/7f0bcd24-0590-49a0-845b-9d5e4e3d3cf3">

**Comment by linkdotnet** [comment]
That said - I am not sure what causes this issue.

**Comment by linkdotnet** [comment]
@diegodrf do you have rc2 of dotnet8 installed?

**Comment by diegodrf** [comment]
Yes. I'm using the .Net 8 RC2 to run this project.

I think it can be something related to IDE. I'm using the Rider EAP. 

After your message about running with the command `dotnet watch`, I ran the project using it and now everything is fine.

I was running the project using the debug button from IDE.

I noted that using the `dotnet watch` the project starts using the port 5049 was configured on `lauchSettings.json` and using the debug button the project starts using the port 5000.

So, I think the issue can be closed.

Thank you for your help.

**Comment by linkdotnet** [comment]
Glad to hear and somewhat interesting.

With the non-EAP version on MacOS - debugging works as expected.
