### ISSUE TITLE
Min(By)/Max(By) behaves incorrectly

### ISSUE THREAD

**Issue by linkdotnet** [linkdotnet/LINQMarbles#6]
Write now there is a `NullReferenceException` due to the using when an empty array is given as input. 

It ideally should throw `SequenceContainsNoElementsException` or simliar.

**Comment by diegodrf** [comment]
The `NullReferenceException` is throwing because the code tries to access a property from a `null` object.

At the **MinBy** page, when `_marbles` is empty `_marbles.MinBy(m => m.Content)` returns `null` and `marble.Color` is trying to access the property.
```csharp
<OutputPanel>
        @{ var marble = _marbles.MinBy(m => m.Content); }
        <Marble Color="marble.Color">@marble.Number,@marble.Content</Marble>
    </OutputPanel>
```

The same occurs on the **Min** page. `@_marbles.MinBy(s => s.Number)!.Number` returns `null` as a result, but the code uses `!` to explicitly force access.
```csharp
<OutputPanel>
        <MudText Typo="Typo.h4">@_marbles.MinBy(s => s.Number)!.Number</MudText>
    </OutputPanel>
```

Why should throw `SequenceContainsNoElementsException`? 
Applying `@if (marble is not null)` isn't enough to solve it?

**Comment by diegodrf** [comment]
I created PR #8 to fix it as I described. 

If you do not agree with this approach or if I misunderstood the problem, please give me more information to help.

**Comment by linkdotnet** [comment]
Yeah I figured out the problem.
There is a difference between:
```csharp
Array.Empty<int>().Max(); // Throws an exception
```

Vs
```csharp
Array.Empty<MyClass>().Max(); // Returns null
```

So the question here should be, do we want an exception or `null` - I would argue an exception instead of "nothing".
So your proposed solution is a good start but I feel we are not quite there yet - at least it doesn't mimic the behavior of LINQ. The marbles for Min/Max are "simple" objects / ValueTypes, whereas MinBy/MaxBy are complex objects (that don't throw).

So for `MinBy`/`MaxBy` I would show a.`null` marble just like in `SingleOrDefault`/`FirstOrDefault` and for `Min`/`Max` an exception should be thrown.

**Comment by diegodrf** [comment]
I saw the code applied on `First` and `FirstOrDefault` and replicated it to these scenarios.

To use `Min` and `Max` on complex objects we need to implement `IComparable`.

I tried to implement `IComparable`, but when the array is empty the thrown exception was about trying to access property on `null` object. Using `Select` to convert the `MarbleNumberModel[]` to `int[]` worked well.

**Comment by linkdotnet** [comment]
Nice work! And thanks again for the fix. I merged the PR - and therefore will close this as resolved!
